repos:
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        args: [--strict, --ignore-missing-imports]
        language: python
        minimum_pre_commit_version: '3.7.0'

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.2
    hooks:
      - id: ruff
        args: [--fix, --select, I]
        language: python
        minimum_pre_commit_version: '3.7.0'
      - id: ruff-format
        language: python
        minimum_pre_commit_version: '3.7.0'
