default_format: json

formats:
  json: src.file_handlers.json_handler.JsonHandler
  npy: src.file_handlers.numpy_handler.NumpyHandler

default_algorithm: kmeans

algorithms:
  kmeans: sklearn.cluster.KMeans
  spectral: sklearn.cluster.SpectralClustering
  dbscan: sklearn.cluster.DBSCAN

hyperparams:
  kmeans:
    n_clusters: 8
  spectral:
    n_clusters: 8
    affinity: nearest_neighbors
  dbscan:
    eps: 0.5
    min_samples: 5
